services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - path: apps/backend/.env
        required: false
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: runner
    depends_on:
      - backend
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
      NITRO_HOST: 0.0.0.0
      PORT: 3000
    ports:
      - '3000:3000'
    restart: unless-stopped
